// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhWvy9vkqM6aiKhqwmWRZNZ-yCg8kbOxc',
    appId: '1:562959505004:web:82dfd6a0404ba41bdcea49',
    messagingSenderId: '562959505004',
    projectId: 'whatapp-backend-a0389',
    authDomain: 'whatapp-backend-a0389.firebaseapp.com',
    storageBucket: 'whatapp-backend-a0389.appspot.com',
    measurementId: 'G-9QJW06TZR1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTEQmRkZjD2X6clU8Gt9f_gMfXsA2PLQ8',
    appId: '1:562959505004:android:41ce57cef1fb4c1cdcea49',
    messagingSenderId: '562959505004',
    projectId: 'whatapp-backend-a0389',
    storageBucket: 'whatapp-backend-a0389.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCi4eKQdZxcTO_nBQHaNEd0dNA6Uz_gbdg',
    appId: '1:562959505004:ios:bf5abfa3816da3aedcea49',
    messagingSenderId: '562959505004',
    projectId: 'whatapp-backend-a0389',
    storageBucket: 'whatapp-backend-a0389.appspot.com',
    iosClientId: '562959505004-0ac31vueonkvkdj2h1aolj4pn3esk8q6.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsappUi',
  );
}
